### PR TITLE
caching AuthConfigFactory without synchronization

### PR DESCRIPTION
**Pull request by sunnypav**
Performance tests showed getting authconfigfactory as the bottleneck. Already authconfigfactory  class itself is caching it but using the class level lock. Avoiding that lock and making the factory retrieval lock free.

### CODE REVIEW

**Comment by markt-asf** [comment]
Given the bottleneck is in Tomcat's AuthConfigFactory, it would be better to fix the problem there.

**Comment by sunnypav** [comment]
The class is from https://mvnrepository.com/artifact/org.apache.geronimo.specs/geronimo-jaspic_1.0_spec/1.1 which tomcat is embedding it i am assuming. The last update to this project happened in 2010. So i dont even know whether that project is active or not. 

Yes it is better to fix problem there but if the project is not active it would be better to fix it here.

**Comment by sunnypav** [comment]
I will try adding to the same library and see how it goes.

**Comment by sunnypav** [comment]
I misunderstood your words will fix this issue in AuthConfigFactory

**Pull request closed without merging**
