### PR TITLE
Using concurrent map to avoid severe lock contention issue

### PR DESCRIPTION
**Pull request by aoindustries**
We have an application that makes heavy use of custom JSP tags.  We are experiencing a severe concurrency bottleneck, with the system falling flat above a concurrency of two and never able to drive more than four CPU cores.

We have profiled and found that, by far, the bottleneck is lock contention on the annotation cache.  This patch replaces the WeakHashMap with a concurrent weak cache.

Before this change, we only operate at 1.89 times throughput going from one core to four.  After this change, we operate at 3.03 times throughput going from one core to four.

### CODE REVIEW

**Comment by aoindustries** [comment]
One observation, the concurrent weak cache implementation performs cleaning on the thread using the cache, and this thread will often be on the critical request path. Perhaps this cache could be cleaned by a background thread (preferrably from a provided ExecutorService) when the calling thread detects it's time to clean.

**Comment by markt-asf** [comment]
Tomcat already has the ManagedConcurrentWeakHashMap implementation. I've switched the annotation cache to use this. Periodic maintenance is handled by the background processor.

**Comment by markt-asf** [comment]
Under high concurrency, a ConcurrentLinkedDeque performs more poorly than the current implementation.   I'll continue to look for better solutions but with TagHandlerPool there is always the option to specify your own custom pool - as you have done in this case.

**Comment by markt-asf** [comment]
The InstanceManager changes have been back-ported to 8.5.x. The TagHandlerPool changes won;t be back-ported. The option remains for applications to provide a custom TagHandlerPool.

**Comment by aoindustries** [comment]
Thank you for your support.

**Pull request closed without merging**
